# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
