# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180509_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='\u9a8c\u8bc1\u952e\u540d')),
                ('exp_value', models.CharField(max_length=100, verbose_name='\u671f\u671b\u503c')),
                ('value', models.CharField(max_length=100, verbose_name='\u5b9e\u9645\u503c')),
                ('is_pass', models.IntegerField(default=0, verbose_name='\u9a8c\u8bc1\u662f\u5426\u901a\u8fc7\uff0c0\uff1awaiting\uff0c1\uff1apass\uff0c-1\uff1afail')),
                ('Result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Result', verbose_name='\u8bf7\u6c42id')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case', verbose_name='caseId')),
            ],
            options={
                'verbose_name': '\u9a8c\u8bc1',
                'verbose_name_plural': '\u9a8c\u8bc1',
            },
        ),
    ]
