# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_plan_runtime_env_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime_env',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='appId'),
        ),
        migrations.AddField(
            model_name='runtime_env',
            name='token_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tokenId'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
