# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180510_2058'),
        ('task', '0002_plan_runtime_env_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime_env',
            name='Proj',
            field=models.ForeignKey(default=id, on_delete=django.db.models.deletion.CASCADE, to='api.Proj', verbose_name='\u6240\u5c5e\u9879\u76ee'),
            preserve_default=False,
        ),
    ]
